import streamlit as st

st.set_page_config(
    page_title="Student Adaptive Practice",
    page_icon="🎓",
    layout="centered"
)

# --------------------------------------------------
# SESSION STATE
# --------------------------------------------------

defaults = {
    "student_started": False,
    "student_name": "",
    "question_number": 1,
    "current_level": 2,
    "answer_submitted": False,
    "student_answer": "",
    "attempts": 0,
    "correct_count": 0,
    "hints_used": 0,
    "history": []
}

for key, value in defaults.items():
    if key not in st.session_state:
        st.session_state[key] = value


# --------------------------------------------------
# DEMO QUESTIONS
# These will later be generated by AI.
# --------------------------------------------------

questions = {

    1: {
        "question": "Factorise:",
        "latex": r"x^2 - 5x + 6",
        "answers": [
            "(x-2)(x-3)",
            "(x - 2)(x - 3)"
        ],
        "hint":
            "Look for two numbers whose product is 6 "
            "and whose sum is -5."
    },

    2: {
        "question": "Solve:",
        "latex": r"x^2 - 5x + 6 = 0",
        "answers": [
            "x=2,3",
            "x = 2, 3",
            "2,3",
            "2, 3",
            "x=2 or x=3",
            "x = 2 or x = 3"
        ],
        "hint":
            "Try factorising the quadratic first."
    },

    3: {
        "question": "Solve:",
        "latex": r"2x^2 - 7x + 3 = 0",
        "answers": [
            "x=3,0.5",
            "x = 3, 0.5",
            "3,0.5",
            "3, 0.5",
            "x=3 or x=0.5",
            "x = 3 or x = 0.5"
        ],
        "hint":
            "Try factorising the expression into two brackets."
    },

    4: {
        "question":
            "A rectangle has an area of 48 cm². "
            "Its length is 2 cm greater than its width. "
            "Find its dimensions.",

        "latex": None,

        "answers": [
            "6 and 8",
            "6,8",
            "6 x 8",
            "6x8",
            "width 6 length 8"
        ],

        "hint":
            "Let the width be x. "
            "Then the length is x + 2."
    },

    5: {
        "question":
            "Explain why a quadratic equation "
            "can have two different solutions.",

        "latex": None,

        # AI will evaluate this type of response later.
        "answers": None,

        "hint":
            "Think about where a quadratic graph "
            "can cross the x-axis."
    }
}


# --------------------------------------------------
# FUNCTIONS
# --------------------------------------------------

def normalise(text):
    return text.lower().replace(" ", "")


def next_question():

    st.session_state.question_number += 1
    st.session_state.answer_submitted = False
    st.session_state.student_answer = ""


def restart_practice():

    st.session_state.student_started = False
    st.session_state.student_name = ""
    st.session_state.question_number = 1
    st.session_state.current_level = 2
    st.session_state.answer_submitted = False
    st.session_state.student_answer = ""
    st.session_state.attempts = 0
    st.session_state.correct_count = 0
    st.session_state.hints_used = 0
    st.session_state.history = []


# --------------------------------------------------
# GET TEACHER SETTINGS
# --------------------------------------------------

topic = st.session_state.get(
    "topic",
    "Quadratic Equations"
)

progression = st.session_state.get(
    "progression",
    {
        1: "Factorise simple monic quadratics",
        2: "Solve quadratic equations by factorisation",
        3: "Solve quadratics requiring rearrangement",
        4: "Apply quadratic equations to contextual problems",
        5: "Explain and justify mathematical reasoning"
    }
)


# --------------------------------------------------
# HEADER
# --------------------------------------------------

st.title("🎓 Adaptive Practice")
st.caption(topic)

st.divider()


# ==================================================
# STUDENT START SCREEN
# ==================================================

if not st.session_state.student_started:

    st.subheader(topic)

    st.write(
        "This practice adapts as you work. "
        "Questions may become more challenging or provide "
        "additional support based on your responses."
    )

    student_name = st.text_input(
        "Your name",
        placeholder="Enter your name"
    )

    if st.button(
        "Start Practice",
        type="primary",
        use_container_width=True
    ):

        if not student_name.strip():

            st.warning(
                "Please enter your name."
            )

        else:

            st.session_state.student_name = student_name
            st.session_state.student_started = True
            st.session_state.question_number = 1
            st.session_state.current_level = 2

            st.rerun()


# ==================================================
# STUDENT PRACTICE
# ==================================================

else:

    level = st.session_state.current_level

    # Prevent level going outside 1–5
    level = max(1, min(level, 5))

    question = questions[level]

    st.write(
        f"**Student:** {st.session_state.student_name}"
    )

    st.caption(
        f"Question {st.session_state.question_number}"
    )

    st.progress(
        min(
            st.session_state.question_number / 5,
            1.0
        )
    )

    st.write(
        f"### Level {level}"
    )

    st.write(
        progression.get(
            level,
            "Adaptive Practice"
        )
    )

    st.divider()

    # --------------------------------------------------
    # QUESTION
    # --------------------------------------------------

    st.write(
        f"### {question['question']}"
    )

    if question["latex"]:

        st.latex(
            question["latex"]
        )

    answer = st.text_area(
        "Your answer",
        key=f"answer_{st.session_state.question_number}",
        disabled=st.session_state.answer_submitted,
        placeholder="Enter your answer here..."
    )


    # ==================================================
    # BEFORE SUBMISSION
    # ==================================================

    if not st.session_state.answer_submitted:

        col1, col2 = st.columns([1, 3])

        with col1:

            if st.button(
                "💡 Hint",
                use_container_width=True
            ):

                st.session_state.hints_used += 1

                st.info(
                    question["hint"]
                )

        with col2:

            if st.button(
                "Submit Answer",
                type="primary",
                use_container_width=True
            ):

                if not answer.strip():

                    st.warning(
                        "Please enter an answer first."
                    )

                else:

                    st.session_state.student_answer = answer
                    st.session_state.answer_submitted = True
                    st.session_state.attempts += 1

                    st.rerun()


    # ==================================================
    # AFTER SUBMISSION
    # ==================================================

    else:

        submitted = normalise(
            st.session_state.student_answer
        )

        # ----------------------------------------------
        # CHECK ANSWER
        # ----------------------------------------------

        if question["answers"] is None:

            # For now, reasoning responses are accepted.
            # Later the AI agent will evaluate them.
            correct = True

        else:

            accepted = [
                normalise(a)
                for a in question["answers"]
            ]

            correct = submitted in accepted


        # ----------------------------------------------
        # FEEDBACK
        # ----------------------------------------------

        if correct:

            st.success(
                "✓ Good work. Your response shows "
                "evidence of understanding."
            )

            st.write("### What's next?")

            if level < 5:

                st.write(
                    "⬆️ Your next question will "
                    "increase the challenge."
                )

            else:

                st.write(
                    "✓ You are currently working at "
                    "the highest level in this pathway."
                )

        else:

            st.warning(
                "Not quite. Let's give you another "
                "opportunity around this skill."
            )

            st.write("### What's next?")

            st.write(
                "↔️ Your next question will stay "
                "around the same level."
            )

            st.info(
                question["hint"]
            )


        # ----------------------------------------------
        # SAVE ATTEMPT
        # ----------------------------------------------

        already_saved = any(
            item["question_number"]
            == st.session_state.question_number
            for item in st.session_state.history
        )

        if not already_saved:

            st.session_state.history.append(
                {
                    "question_number":
                        st.session_state.question_number,

                    "level":
                        level,

                    "answer":
                        st.session_state.student_answer,

                    "correct":
                        correct
                }
            )

            if correct:
                st.session_state.correct_count += 1


        # ----------------------------------------------
        # NEXT QUESTION
        # ----------------------------------------------

        if st.button(
            "Next Question →",
            type="primary",
            use_container_width=True
        ):

            if correct and level < 5:

                st.session_state.current_level += 1

            # Incorrect answers remain at same level

            next_question()

            st.rerun()


    # ==================================================
    # STUDENT PROGRESS
    # ==================================================

    st.divider()

    with st.expander("📊 My Progress"):

        st.write(
            f"**Questions attempted:** "
            f"{st.session_state.attempts}"
        )

        st.write(
            f"**Correct responses:** "
            f"{st.session_state.correct_count}"
        )

        st.write(
            f"**Hints used:** "
            f"{st.session_state.hints_used}"
        )

        st.write(
            f"**Current level:** "
            f"{st.session_state.current_level}"
        )

    st.write("")

    if st.button("Restart Practice"):

        restart_practice()

        st.rerun()